/// Maps ISO language codes (stored in settings) to full names for Gemma prompts.
const Map<String, String> kLanguageCodeToName = {
  'Afrikaans': 'Afrikaans',
  'Albanian': 'Albanian',
  'Amharic': 'Amharic',
  'Arabic': 'Arabic',
  'Armenian': 'Armenian',
  'Assamese': 'Assamese',
  'Awadhi': 'Awadhi',
  'Azerbaijani': 'Azerbaijani',
  'Balinese': 'Balinese',
  'Bengali': 'Bengali',
  'Bikol': 'Bikol',
  'Bulgarian': 'Bulgarian',
  'Burmese': 'Burmese',
  'Cantonese': 'Cantonese',
  'Catalan': 'Catalan',
  'Cebuano': 'Cebuano',
  'Chinese (Simplified)': 'Chinese (Simplified)',
  'Chinese (Traditional)': 'Chinese (Traditional)',
  'Corsican': 'Corsican',
  'Czech': 'Czech',
  'Danish': 'Danish',
  'Dutch': 'Dutch',
  'English': 'English',
  'Esperanto': 'Esperanto',
  'Filipino (Tagalog)': 'Filipino (Tagalog)',
  'Finnish': 'Finnish',
  'French': 'French',
  'Galician': 'Galician',
  'Georgian': 'Georgian',
  'German': 'German',
  'Greek': 'Greek',
  'Gujarati': 'Gujarati',
  'Haitian Creole': 'Haitian Creole',
  'Hausa': 'Hausa',
  'Hebrew': 'Hebrew',
  'Hindi': 'Hindi',
  'Hungarian': 'Hungarian',
  'Icelandic': 'Icelandic',
  'Ilocano': 'Ilocano',
  'Indonesian': 'Indonesian',
  'Italian': 'Italian',
  'Japanese': 'Japanese',
  'Javanese': 'Javanese',
  'Kannada': 'Kannada',
  'Kazakh': 'Kazakh',
  'Khmer': 'Khmer',
  'Korean': 'Korean',
  'Krio': 'Krio',
  'Kyrgyz': 'Kyrgyz',
  'Lao': 'Lao',
  'Latin': 'Latin',
  'Latvian': 'Latvian',
  'Lithuanian': 'Lithuanian',
  'Luxembourgish': 'Luxembourgish',
  'Macedonian': 'Macedonian',
  'Maithili': 'Maithili',
  'Malagasy': 'Malagasy',
  'Malay': 'Malay',
  'Malayalam': 'Malayalam',
  'Maltese': 'Maltese',
  'Maori': 'Maori',
  'Marathi': 'Marathi',
  'Mongolian': 'Mongolian',
  'Nepali': 'Nepali',
  'Norwegian': 'Norwegian',
  'Occitan': 'Occitan',
  'Odia': 'Odia',
  'Pashto': 'Pashto',
  'Persian': 'Persian',
  'Polish': 'Polish',
  'Portuguese': 'Portuguese',
  'Punjabi': 'Punjabi',
  'Romanian': 'Romanian',
  'Russian': 'Russian',
  'Sanskrit': 'Sanskrit',
  'Sardinian': 'Sardinian',
  'Serbian': 'Serbian',
  'Shona': 'Shona',
  'Sindhi': 'Sindhi',
  'Sinhala': 'Sinhala',
  'Slovak': 'Slovak',
  'Somali': 'Somali',
  'Spanish': 'Spanish',
  'Sundanese': 'Sundanese',
  'Swahili': 'Swahili',
  'Swedish': 'Swedish',
  'Syriac': 'Syriac',
  'Tajik': 'Tajik',
  'Tamil': 'Tamil',
  'Telugu': 'Telugu',
  'Thai': 'Thai',
  'Turkish': 'Turkish',
  'Turkmen': 'Turkmen',
  'Ukrainian': 'Ukrainian',
  'Urdu': 'Urdu',
  'Uzbek': 'Uzbek',
  'Vietnamese': 'Vietnamese',
  'Yiddish': 'Yiddish',
  'Zulu': 'Zulu',
};

String languageDisplayName(String code) =>
    kLanguageCodeToName[code] ?? code;

const List<String> kTargetLanguageNames = [
  'Amharic',
  'Arabic',
  'Bengali',
  'Burmese',
  'Cantonese',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Dutch',
  'English',
  'Filipino (Tagalog)',
  'French',
  'German',
  'Gujarati',
  'Hausa',
  'Hindi',
  'Indonesian',
  'Italian',
  'Japanese',
  'Javanese',
  'Kannada',
  'Korean',
  'Malay',
  'Malayalam',
  'Marathi',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Russian',
  'Spanish',
  'Swahili',
  'Tamil',
  'Telugu',
  'Thai',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Vietnamese',
];
